image: oven/bun:1

variables:
  GIT_DEPTH: 0 # Clone the entire repository for lastUpdated

pages:
  cache:
    paths:
      - node_modules/

  script:
    - bun install --frozen-lockfile
    - bun run build
    - rm -rf public
    - mv dist public

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH